---
title: "Usage of the hFDR procedure with Gaussian Linear models"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GaussianLinear}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---



```{r, results='hide', message=FALSE, warning=FALSE}
set.seed(2024)
```

```{r define-problem}
set.seed(2024)

# Problem parameters
n <- 300          # number of observations
p <- 10           # number of variables
k <- 10            # number of variables with nonzero coefficients
amplitude <- 3.5   # signal amplitude (for noise level = 1)

# Generate the variables from a multivariate normal distribution
mu <- rep(0,p)
rho <- 0.25
Sigma <- toeplitz(rho^(0:(p-1)))
X <- t(t(matrix(rnorm(n*p),n) %*% chol(Sigma)) + (1:p)*0)

# Generate the response from a linear model
nonzero <- sample(p, k)
beta <- amplitude * (1:p %in% nonzero) / sqrt(n)
y.sample <- function(X) X %*% beta + rnorm(n) + 1000
y <- y.sample(X)

# generate lamabda sequence for lasso
gene_lambda <- function(X, y){
  n <- NROW(X)
  p <- NCOL(X)
  
  y <- scale(y, center = T, scale = F)
  X <- scale(X, center = T, scale = F)
  X <- scale(X, center = F, scale = sqrt(colSums(X^2)/n))
  
  lambda_max <- max(abs(t(X) %*% y)) / n
  sigma <- sqrt(sum(lm(y ~ X)$residuals^2) / (n-p-1))
  lambda_min <- sigma / n
  n_lambda <- 10
  lambda_seq <- lambda_max * (lambda_min/lambda_max)^((0:n_lambda)/n_lambda)
  
  return(lambda_seq)
}
lambda <- gene_lambda(X, y)
```

First examples
--------------

To begin, we call `hFDR` with the default settings.
```{r hFDR-default, results='hide', message=F, warning=F}
# library(hFDR)
# library(tictoc)
# select <- function(X, y, lambda){
#   res <- glmnet::glmnet(X, y, lambda = lambda,
#                         intercept = T, standardize = T,
#                         family = "gaussian")
#   res <- as.matrix(res$beta != 0)
# }
# psi <- function(X, y, variables, threshold = 0.1){
#   tvals <- lm_to_t(X, y)
#   pvals <- pvals_t(tvals$tvals, tvals$df, side = "two")[variables]
#   psi <- 2*(pvals > threshold)
#   normalizer <- 2*rep(1 - threshold, length(variables))
# 
#   return(list(psi = psi, normalizer = normalizer))
# }
# X.mean = (1:p)*0
# psi <- function(X, y, variables){
#   psi.modelX.gauss(X, y, variables, X.mean = X.mean, X.cov = Sigma, threshold = 0.1)
# }
# 
# modelX <- list(
#   sampler.modelX = function(X, ind, sample_size, storage = NULL){
#     sampler.modelX.gauss(X, ind, X.mean = X.mean, X.cov = Sigma, sample_size, storage)
#   },
#   predict.mle = function(X.new, X, y, lambda){
#     predict.model(X.new, X, y, select, lambda, predict.mle.gausslinear)
#   }
# )
# 
# tic()
# result <- hFDR(X, y, model = "gaussgraph", modelX = modelX,
#                select = select.glasso, lambda = lambda, psi = "pval", se = T,
#                n_sample.hfdr = 20, n_sample.se = 10, n_cores = 1)
# toc()
```


```{r hFDR-cv, results='hide', message=F, warning=F}
# library(hFDR)
# library(glmnet)
# lasso.cv <- cv.glmnet(X, y, lambda = lambda, alpha = 1, nfolds = 10,
#                       intercept = T, standardize = T, family = "gaussian")
# hFDR.obj <- hFDR(X, y, model = "gausslinear", select = "lasso",
#                  lambda = lasso.cv$lambda, nlambda = 40, n_cores = 14)
# 
# plot(hFDR.obj, lasso.cv)
```

